//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCrudAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public string ID { get; set; }
        public string BrandID { get; set; }
        public string Model { get; set; }
        public string Power { get; set; }
        public string Color { get; set; }
        public Nullable<int> NDoor { get; set; }
    
        public virtual Brand Brand { get; set; }
    }
}
